### ISSUE TITLE
Failure("Did not expect BoundT") and other weird errors when using polymorphic classes

### ISSUE THREAD

**Issue by pasha-mf** [facebook/flow#1296]
Consider the following test case (I tried to narrow it down as far as I could). Basically I'm trying to declare a Base class containing some State sub-component, however the State should carry a reference to its parent. Seems simple enough?

### Base.js
```
// @flow
import State from "./State.js";

export default class Base<S: State> {
  _state: S;

  get state(): S {
    return this._state;
  }

  set state(newState: S) {
    this._state = newState;
  }
}
```

### State.js
```
import Base from "./Base.js";

export default class State<T: Base> {
  _base: T;

  constructor(base: T) {
    this._base = base;
  }
}
```

### Foo.js
```
// @flow
import Base from "./Base.js";
import State from "./State.js";

class FooState extends State<Foo> {}

class Foo extends Base<FooState> {
  constructor() {
    super();
    this._state = new FooState(this);
  }
}
```

This produces 7 error messages (with Flow 0.20.1, latest build). The first one is `Failure("Did not expect BoundT")` in Base.js:0, and the rest are even less helpful: `Foo. This type is incompatible with >>Base<< union: Base(s).`; `Foo. Expected polymorphic type instead of >>Base<< exports`, `>>Base<< exports. Ineligible value used in/as type annotation (did you forget 'typeof'?)`, etc.

Ok, so in this particular case I was actually able to figure out what gave Flow such a scare. Can you? Hint: it's none of the lines that reportedly contain errors.

[spoiler] So the culprit was the `set state` method in Base. Replacing that with `setState` makes all errors disappear. And it looked so innocent...

**Comment by samwgoldman** [comment]
The circular dependency between State and Base is pretty interesting here. I wonder if that's related?

**Comment by pasha-mf** [comment]
Well, it's possible that the setter attempts to verify the type of its argument, and then is unable to handle the loop in type declarations.

**Comment by mroch** [comment]
pretty sure we fixed this one a while back (I remember "Did not expect BoundT"). please reopen if you can still repro. thanks!

**Comment by lammertw** [comment]
I'm still receiving this error whenever I create a polymorphic class with a setter in it.
