### ISSUE TITLE
Flow still errors tries to parse files that have @noflow in them

### ISSUE THREAD

**Issue by Gozala** [facebook/flow#1321]
Here is my example:

### `b.js`

```js
/* @flow */

import * as a from "./a";
```

### `a.js`

```js
/* @noflow */

var nothing = exports.nothing = function nothing(){
  return (/*:Nothing*/null
  );
};
```

### `stdout`

```
.js:4
  4:   return (/*:Nothing*/null
               ^^^ Unexpected token /*:

b.js:3
  3: import * as a from "./a";
                        ^^^^^ ./a. Required module not found


Found 2 errors
```

Side Note: Babel has several bugs that cause it to output invalid flow annotations as in  `a.js`. But even adding a `@noflow` to try and mitigate does not work. Also there is another babel bug that does not stip out flow comments if flow-syntax plugin is used which is required to handle files with flow extensions.

**Comment by samwgoldman** [comment]
Thanks for the report. I think the solution here is to treat all comments as just comments in `@noflow` mode. Should be fixed in the near term.

**Comment by mroch** [comment]
So, some clarification:

- no pragmas means "parse the file as a normal JS file." if you have inline types like `(123: number)`, this is a parse error because the type syntax is not valid normal JS. this also helps catch mistakes where people add annotations but forget to add `@flow`, so they don't realize that none of their annotations are being checked.
- `@flow` means "parse the file with types allowed, and run Flow"
- `@noflow` means "parse the file with types allowed, but suppress all the errors." this is meant as an escape hatch to suppress flow without having to delete all the annotations.

In this case, flow is working as expected. In `@noflow` mode, it's parsing types and hitting a syntax error... `return (:Nothingnull);` is invalid. However, you should've been able to remove the pragma entirely and have it parse as a normal comment, but that was broken. Thanks for raising that issue, fixed in https://github.com/facebook/flow/commit/6c88420786dc42ef60123a44faf5ae34456acebc!

**Comment by vjpr** [comment]
@mroch

I'm seeing this too.

If I use `options.all`, and then add `// @noflow` to my file, I expect to get no errors from that file.

But I am still getting `Property not found in` errors.

Does the `all` option override the `noflow`?

**Comment by aleclarson** [comment]
Is this on the roadmap?
