### ISSUE TITLE
Unable to Curry Polymorphic Functions

### ISSUE THREAD

**Issue by mwalkerwells** [facebook/flow#2563]
**Unable to append type params to composed function:**
![screen shot 2016-10-02 at 9 04 21 pm](https://cloud.githubusercontent.com/assets/16157429/19027324/13f4b25e-88e4-11e6-89cd-40bf0aa593b5.png)

**If you place type params inside the curry function, no error & it compiles**
![screen shot 2016-10-02 at 9 04 03 pm](https://cloud.githubusercontent.com/assets/16157429/19027325/140cc010-88e4-11e6-937f-263bd61389a4.png)

**BUT, you cannot have two of these functions back to back. Flow doesn't throw an error, but it does not compile, since the type params are not stripped**
![screen shot 2016-10-02 at 9 05 29 pm](https://cloud.githubusercontent.com/assets/16157429/19027321/0dbb3782-88e4-11e6-87b5-7f6a97cb0393.png)
<img width="491" alt="screen shot 2016-10-02 at 9 05 39 pm" src="https://cloud.githubusercontent.com/assets/16157429/19027322/0fd590ee-88e4-11e6-8e80-6864653bda74.png">

**Comment by erikdesjardins** [comment]
> the type params are not stripped

That's a Babel issue (https://github.com/babel/babel/issues/4483), which was fixed in [Babel 6.16.0](https://github.com/babel/babel/releases/tag/v6.16.0)

**Comment by mwalkerwells** [comment]
Ah, nice. Thanks!

**Comment by mwalkerwells** [comment]
Eh, actually, looks like that is a different issue. Still doesn't work on 6.16.0

**Comment by samwgoldman** [comment]
This doesn't look like a Flow error to me. Is it possible that the dependency which is emitting this error is not using that version of Babel?

**Comment by mwalkerwells** [comment]
Doesn't work on babeljs.io, which is currently using 6.17: https://goo.gl/LU49pG

**Comment by mwalkerwells** [comment]
I'm building with webpack & babel and have a pretty simple setup. Still can't figure it out. :(

**package.json**
```json
  "dependencies": {
    "chokidar": "1.6.0",
    "classnames": "2.2.5",
    "express": "4.14.0",
    "express-graphql": "0.5.4",
    "graphql": "0.7.0",
    "graphql-relay": "0.4.3",
    "react": "^15.3.1",
    "react-dom": "^15.3.1",
    "react-relay": "0.9.3",
    "require-clean": "0.1.3"
  },
  "devDependencies": {
    "babel-cli": "^6.14.0",
    "babel-core": "^6.17.0",
    "babel-loader": "^6.2.5",
    "babel-plugin-transform-flow-strip-types": "^6.14.0",
    "babel-polyfill": "^6.13.0",
    "babel-preset-es2015": "^6.14.0",
    "babel-preset-react": "^6.11.1",
    "babel-preset-stage-0": "^6.5.0",
    "babel-relay-plugin": "0.9.3",
    "flow-bin": "^0.33.0",
    "webpack": "1.13.2",
    "webpack-dev-server": "1.15.1"
  }
```

**.babelrc**
```json
{
  "passPerPreset": true,
  "presets": [
    {
      "plugins": [
        "./build/babelRelayPlugin",
        "transform-flow-strip-types"
      ]
    },
    "react",
    "es2015",
    "stage-0"
  ]
}
```

**webpack compiler config**
```javascript
  const compiler = webpack({
    entry: path.resolve(__dirname, 'js', 'app.js'),
    debug: true,
    devtool: 'inline-source-map',
    module: {
      loaders: [
        {
          exclude: /(node_modules|flow-static-land)/, // Workaround for locally installed package: https://github.com/webpack/webpack/issues/1866
          loader: 'babel',
          test: /\.js$/,
        }
      ]
    },
    output: {filename: '/app.js', path: '/', publicPath: '/js/'}
  });
```

**Comment by mwalkerwells** [comment]
**So the simplest setup DOES work:** :(
[babel-test.zip](https://github.com/facebook/flow/files/511982/babel-test.zip)

**I mean, the Atom language-babel package doesn't like the syntax:**
![screen shot 2016-10-05 at 11 07 02 am](https://cloud.githubusercontent.com/assets/16157429/19125424/de7abe2a-8aeb-11e6-8196-98f453eca51a.png)
https://github.com/gandm/language-babel

**Comment by mwalkerwells** [comment]
@samwgoldman I actually narrowed it down to the babel react preset

![screen shot 2016-10-05 at 12 29 06 pm](https://cloud.githubusercontent.com/assets/16157429/19128266/78e19c44-8af7-11e6-9094-66c3f4bdf17b.png)

**Minimal example:**
[babel-test.zip](https://github.com/facebook/flow/files/512154/babel-test.zip)
