### ISSUE TITLE
Can't import {Buffer} from 'buffer', same with EventEmitter/events

### ISSUE THREAD

**Issue by josephsavona** [facebook/flow#3723]
Flow (tested with 43 and 42) rejects the following line, claiming that `buffer` does not have an export named `Buffer`:

```
import {Buffer} from 'buffer';
```

It allows `import Buffer from 'buffer'`, except that this doesn't work: 'buffer' doesn't export a `default` value, so that throws when compiling ES6 imports to require statements e.g. with Babel. 

The same is true for `import {EventEmitter} from 'events'`, which works but is rejected by Flow.

The use case I'm trying to solve is explicitly Buffer/EventEmitter so that I can produce node builds (using the actual node modules) and browser builds (rewriting those imports to 'buffer/' and 'events/') that require browser polyfills for them.

**Comment by gre** [comment]
this is still not fixed? 

despite the PR that was supposed to support Buffer, I'm having it uncovered:

<img width="627" alt="capture d ecran 2018-10-20 a 10 31 11" src="https://user-images.githubusercontent.com/211411/47253458-4e8c6d00-d453-11e8-930f-049d34f90f47.png">

tried both require() and import syntaxes

**Comment by Brianzchen** [comment]
@gre this was fixed to a degree. There's no flow error anymore because `Buffer` is defined in `buffer` but it's just not typed properly so it defaults to `any`.

I think in general this issue is resolved. Though looking at the definition, I don't know why it was defined as `Buffer: typeof global.Buffer` instead of `Buffer: Buffer` which may make it more useful

**Comment by kvnloughead** [comment]
Still not working for me. I  get 'import not found: Buffer'.

![image](https://user-images.githubusercontent.com/37159177/166841993-8bfdb28e-dd1a-4efd-a549-d19885961756.png)

**Comment by SamChou19815** [comment]
The libdef has been moved to flow-typed. If you want to make improvements, please make PR over there.
