### ISSUE TITLE
Opaque subtypes of string cannot be used as object keys

### ISSUE THREAD

**Issue by wchargin** [facebook/flow#6569]
If `T` is a transparent subtype of `string`, then an instance of `T` can
naturally be used as a key in an object. But [the same does not hold if
`T` is an opaque subtype of string][1]:

```js
// @flow
declare opaque type SpecialString: string;
declare var specialString: SpecialString;

// Even though `specialString` is a `string`, we can't use it as a key:
const bad1 = {[specialString]: 1};
const bad2: {[SpecialString]: number} = {[specialString]: 2};

// If we explicitly up-cast it to `string`, the expression typechecks
// (surprisingly), and things look okay...
const looksOkay3: {[SpecialString]: number} = {[(specialString: string)]: 3};
// ...but we suffer from https://github.com/facebook/flow/issues/6568:
const bad4: {[SpecialString]: number} = {[(specialString: string)]: "I am not a number"};

// If we do somehow get a useful reference to a value of such a type,
// then we can interact with it without problem...
declare var magic5: {[SpecialString]: number};
magic5[specialString] = 5;
// ...except for the (unrelated?) problem that `Object.keys` is useless.
const keys: $ReadOnlyArray<SpecialString> = Object.keys(magic5);

// To prove beyond any doubt---`specialString` really is a `string`:
const phew: string = specialString;
```

As noted in the above code, #6568 makes a potential workaround untenable.

[1]: https://flow.org/try/#0PTAEAEDMBsHsHcBQATApgY2gQwE6tLAA5YCOArvgC4Ceh+AynegJZbT2U7MB2A5gFygAzpx68A3CgzY8oAG65hTVu1F9BjDCo5c+kxCFABROam6hKAC1hlel0AAMhytjrEPQzIaCyORu3gcAGlB4fHQsbgBySlAyIXxmWKxvXwBrVGp+RHRYbhFQACMsZABGUABeUABvAG1nLVc1XgBdQVKAX0lc-Nji5AAmQTrNFiaAttBuMgBbQtQcDsqa+pdVCcEBrsQDMABJSFD8VAAPQmhmFkpoajjCAFoIgqSLWD9m4ItLY7O8ISFmHkLLQMN90GkhLtQAAKIRkHCELgAvg3ACUIUiyC+Ym8cFgaQIaSw1AAdGScnkCniIQB5InUADMw1qo20zUm0zmCyWVTqsLWbnUwmaqMmDO2hjJJMKZFiYWEZEgkAWoEgOFgM1AlkolEIQn4IF4SUsZEKJNyM2AkCw6FQhVg+KtcHgwC8cNQQmAADYAKxegAc2R6BX6ABZmazxmIObN5otlnyGmN1mJBP4xKLBAAiPY+TXcWDJKaxhZZ7ZQg5HUDIN5CDWoazwUC8VBF+KoSBkaCgPDKvDcW2vHzyNgUAiHOHoey+Gh0IJQqxmKsRcw8SgLG1y42eLdWGyxRGwQrQVAzKVSTC4fAKHCgGZYI3oH0RgXswScuPbe+Pn2rRopvgWmWH1JElMlTltQhYkgWBb0XGEyG4PBsHXZAAH5UVAQ9j1PL4sFiBwaUKAArDBKBJDJqCEDwvDiBIT3+EkKV6UBKP1UAABIACVUBKGluBuABBHAcGJAAeSMAN4AA+ZYiNI9ByLY6Fv0uH1UX0QwABU3kPUwikyPIsUiW4a1NSh7kspxXwCDw8DYG5PFSd5bKDSkD2+eA02aZYkzZAJJCAA

**Comment by wchargin** [comment]
Update: This appears to have been addressed in 0b2dbd4fd1c1fa0e864b1f452f6ad99a490e6639, but then reverted in d2a4faa8831d37502a3ab4a1d38fec66d62d158a.

Let me know if there’s anything that I can do to help!

**Comment by gajus** [comment]
Ay reason this was never fixed?

**Comment by jbrown215** [comment]
We had an invariant that my fix violated. I still have a task filed for it.

**Comment by SamChou19815** [comment]
This is now supported
