### ISSUE TITLE
Union Type and destructuring

### ISSUE THREAD

**Issue by pladaria** [facebook/flow#6805]
Looks like flow is losing type info when extracting some property of a Union Type variable:

```javascript
/* @flow */

type Action = 
  | {type: 'A', payload: string}  
  | {type: 'B', payload: number};

// OK
const f1 = (action: Action) => {
  switch (action.type) {
    case 'A': return action.payload.length;
    case 'B': return action.payload + 10;
  }
}


// Not OK
const f2 = ({type, payload}: Action) => {
  switch (type) {
    case 'A': return payload.length;
    case 'B': return payload + 10;
  }
}
```
[flow.org/try](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgCCAxhgJZwB2YAvGKmGAD5gDe2+AXGAOSE8AaMDgCGWeCIAm3AM4YATmUoBzAL6MGzNhzzceAIUHCxE6WEoBXALYAjPPNUBudMGBgA8gGlUxKnLBQAIy0YAAUIqQUlNwk5FQAlLQAfGyaMghkGMQAFmERcZQAdDqJrJqMxCIyBHw83PJ4GBby1PlRhaLicFKFMHgqGNnOjBVVNYb1jc2tkVQdJt2SYADUYIEADMNgqqg7Lm4AcnAYHt6+lP5QAEwhoey4eEKdpqoxs5SJNClljOmZOWESqkRmBKtVePxJk0WsYuj0+gMhuVQWNeBMwA1odRnosVmtNpodqogA)

Is this a bug or the expected behavior?

**Comment by villesau** [comment]
Similar problem with exact types: [try flow](https://flow.org/try/#0JYWwDg9gTgLgBAKjgQwM5wEoFNkGN4BmUEIcA5FDvmQFA0wCeYWcAygK4BGAjAArFh0AXjgBvAD4oAXHAB27EJyxQANHE4z5i5XHEBfANz0mLDpwBM-CILgiJ0uKhhRgsgOZrcMpy-e7DdLgQsk5sXNy2cAAUYAKoMmZ8cQCUtgB8cAA8ACbAAG5wAPRpRkEh8GbmkTFxCVyWKelZuQXFRjRloQDCJNWiNHCOWAA2WPjQKgNwAHSzsdaoNHoy9qgjYzDQMs7sWGqz04lWNvq6YpJro+NQMgTIw2v7s5XH6PqpQmlTlxvQcAD8WUSYgO80EeiKGRkmUqILmcQhbSAA)

**Comment by goodmind** [comment]
Was fixed in https://github.com/facebook/flow/commit/de994b684b3b0561df4e596e0a46b63a93d70a33

```
/* @flow */

type Action = 
  | {type: 'A', payload: string}  
  | {type: 'B', payload: number};

// OK
const f1 = (action: Action) => {
  switch (action.type) {
    case 'A': return action.payload.length;
    case 'B': return action.payload + 10;
  }
}

// OK
const f2 = (action: Action) => {
  switch (action.type) {
    case 'A': 
      return action.payload.length;
    case 'B': 
      return action.payload + 10;
    default:
      ;(action.type: empty)
  }
}
```

[Try Flow](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgCCAxhgJZwB2YAvGKmGAD5gDe2+AXGAOSE8AaMDgCGWeCIAm3AM4YATmUoBzAL6MGzNhzzceAIUHCxE6WEoBXALYAjPPNUBudMGBgA8gGlUxKnLBQAIy0YAAUIqQUlNwk5FQAlLQAfGyaMghkGMQAFmERcZQAdDqJrJqMxCIyBHw83PJ4GBby1PlRhaLicFKFMHgqGNnOjBVVNYb1jc2tkVQdJt2SYADUYIEADMNgqqg7qK4e3r6U-lAATCHhs9FE14k0KWWM6Zk5edfFuHil5WCV1bx+NxfowGk0WmA2nNOqZev1lIMtqMAQY6vQRiMwdNIR8YYsVmtNr9JHgoCILDAMJwQWBHFcCp8uGA8FYcNh4podqogA)

**Comment by pladaria** [comment]
@goodmind  Are you sure this issue is really fixed?

The case reported in this issue is still failing in master

**Comment by goodmind** [comment]
Ah, sorry, I think it is impossible to fix this kind of destructuring

**Comment by villesau** [comment]
I don't think it's impossible, but for sure it's difficult. In optimal case flow would be able to track variables that's result of desctructuring just like object proerties.
