### ISSUE TITLE
Unsoundness when mutable objects are used (`false` has type `true`)

### ISSUE THREAD

**Issue by aij** [facebook/flow#6893]
I think this is due to a problem with unification: (Tested on v0.80.0)

```javascript
const a = {x: true};         // A mutable object.
const b:{x: true} = a;       // Works
const c:{x: boolean} = a;    // Also works...
c.x = false;                 // Uh oh. This can't be good...
const derp:true = b.x;       // Egads! false:true
```

[Try it](https://flow.org/try/#0MYewdgzgLgBAhjAvDA3gDwFwygJwK4CmAvgNwzkUUD0VMAgjALZ5RwBGANgTCGwFYFgUAHQAoUJFhsM6LLkJEk8MpXI0YAdRA4A1hHHhoMYDMww2IEFzhhFyOCrW06HCCBgB3bXuG-xwtCUAMzhXAkdVSOpaAFUACx444RgAFTiASwhjGwByKW4Ac0sAE18xCSNighwABwx5bmQ2AIjomABRArhiiABCGBCw+vwCIA)

I was trying to explain how in a Hindley-Milner style type inference system, subsequent type annotations will influence the types inferred earlier through unification, but it wasn't working as I expected. Ordering shouldn't matter of course, but changing the order of `b` and `c` above does produce a type error as would be expected of a sound type system.

#5895 may or may not be more than tangentially related...

**Comment by wchargin** [comment]
Just to be clear, [this yields `coerce`:][1]

```js
// @flow
function coerce<T, U>(t: T): U {
  class Unique {}
  type Box<E> = {x: E};
  const box = {x: new Unique()};
  const xob = (box: Box<U | Unique>);
  (box: Box<mixed>);
  box.x = t;
  if (xob.x instanceof Unique) throw new Error("Unreachable.");
  return xob.x;
}
```

[1]: https://flow.org/try/#0PTAEAEDMBsHsHcBQkCuA7AxgFwJazaBrAKYBOGxAPACoA0oAqgHwAUWAXKNQJScOgBvRKELQAhgGcJoAMIlyZQcJGF8ErKRTZYpFt0EBfZSJwATFgA99A0KWJYUpAhYDcoIyI+gAgqVJiATwA6SFJYAFsWFgBtAF1OOTIKUjjubjdQEFAA4gl6LAALHGloHDRiUGLbYgBHFBw7U2U7BydQcvhZeWS9ILM2dMQjIA

(Thanks for posting.)

**Comment by SamChou19815** [comment]
fixed

**Comment by mwiencek** [comment]
@SamChou19815 It looks like you can still reproduce the boolean example from the OP in v0.274.0: [Try Flow](https://flow.org/try/#1N4Igxg9gdgZglgcxALlAIwIZoKYBsD6uEEAztvhgE6UYCe+JADpdhgCYowa5kA0I2KAFcAtiRQAXSkOz9sADwxgJ+NPTbYuQ3BMnTZA+Y2yU4IwRO4A6SFBIrGVDGM7c+h46fNRLuKxJIGWh8MeT0ZfhYlCStpHzNsFBAMIQkIEQwJODAQfiEyfBE4eWw2fDgofDBMsAALfAA3KjgsXGxxZC4eAw0G-GhcWn9aY3wWZldu-g1mbGqJUoBaCRHEzrcDEgBrbAk62kXhXFxJ923d-cPRHEpTgyEoMDaqZdW7vKgoOfaSKgOKpqmDA+d4gB5fMA-P6LCCMLLQbiLOoYCqgh6-GDYRYIXYLSgkRZkCR4jpddwPfJLZjpOBkUEKTwJEJ+DAkMiUFSwkyZCC3dbdAC+-EgGiStnsAAIMBKALwS4DyZASqQyKUkCXiiQCgDcEr1AHp9RKAIISkSpVrYCUQNAAKzmMQAOo9oJK0KhFcr9ALZVLdXqA4HDRKAOq8rYkZ2ajUepVoYjPKA+uUYf2BiXB408CASgDu4ZIViLUas8l9ZOwafT1erwYAqrVrbUrBKACq1Wka4EAcgkEpwEoQxDYRasUddfY0lEYyBVVrlaFLVdrRoAogh2CQAIQSiuz-S5EANEwkODQJINAAMVgATAB2AAsVkvIAFQA)

**Comment by SamChou19815** [comment]
fixed in 0.275
