### ISSUE TITLE
Flow does not report any errors

### ISSUE THREAD

**Issue by joa** [facebook/flow#7599]
Flow version: `Flow, a static type checker for JavaScript, version 0.95.1`

## Expected behavior
Type errors are reported.

## Actual behavior
No type errors are being reported.

This is not reproducible with the file in question and I can't share the repository. I am happy to provide any additional information or do any sorts of debugging necessary.

An obvious error, like `function f(x: number): number { return x }` with `f("foo")` is not reported by flow although `type-at-pos` reports the correct types for both the function call as well as the declaration. `flow ls` also contains the file in question.

If in introduce the same error in a smaller file at the top-level of my project it is correctly reported.

.flowconfig:
```

[ignore]

[include]

[libs]

[lints]

[options]

[strict]
```

I am sorry for not being able to provide a reproducible use-case or more information. I also don't know at which Flow version this issue started to appear. Only that 0.94.x had the same issue.

**Comment by goodmind** [comment]
@joa did you try `flow stop`?

**Comment by joa** [comment]
@goodmind Yes. As well as `flow focus-check file-in-question.js`

**Comment by goodmind** [comment]
@joa was your editor open during that check, or terminal only?

**Comment by joa** [comment]
I did have the editor open. I re-tested this with the editor being closed and ensuring no node and/or flow process was still active. The result is the same.

However it does seem like I am getting _some_ errors but just not all. For instance, I added another error in a different file and that error was reported correct.

**Comment by joa** [comment]
VS Code says that there is 0% coverage from flow. 

There is a `// @flow` header present and when I try to create a minimal working example, I never encounter the  issue and get the appropriate error.

**Comment by joa** [comment]
Here is some more output:

```
> flow stop; flow coverage ./src/sdk/http/assets.js 
Trying to connect to server for `/Users/joa/Development/app-web-livevideocloud`
Told server for `/Users/joa/Development/app-web-livevideocloud` to die. Waiting for confirmation...
Successfully killed server for `/Users/joa/Development/app-web-livevideocloud`
Launching Flow server for /Users/joa/Development/app-web-livevideocloud
Spawned flow server (pid=42869)
Logs will go to /private/tmp/flow/zSUserszSjoazSDevelopmentzSapp-web-livevideocloud.log
Monitor logs will go to /private/tmp/flow/zSUserszSjoazSDevelopmentzSapp-web-livevideocloud.monitor_log
Covered: 54.52% (181 of 332 expressions)

> flow stop; flow check ./src/sdk/http/assets.js
Trying to connect to server for `/Users/joa/Development/app-web-livevideocloud`
Told server for `/Users/joa/Development/app-web-livevideocloud` to die. Waiting for confirmation...
Successfully killed server for `/Users/joa/Development/app-web-livevideocloud`
Found 0 errors

> flow stop; flow focus-check ./src/sdk/http/assets.js
Trying to connect to server for `/Users/joa/Development/app-web-livevideocloud`
Warning: no server to kill for `/Users/joa/Development/app-web-livevideocloud`
[2019-03-29 14:25:22.874] Checking 1 files
[2019-03-29 14:25:22.885] executable=/Users/joa/.config/yarn/global/node_modules/flow-bin/flow-osx-v0.95.1/flow
[2019-03-29 14:25:22.885] version=0.95.1
[2019-03-29 14:25:22.885] No saved state available
[2019-03-29 14:25:22.886] Parsing
[2019-03-29 14:25:27.143] Building package heap
[2019-03-29 14:25:27.347] Loading libraries
[2019-03-29 14:25:28.187] Resolving dependencies
[2019-03-29 14:25:29.466] to_merge: Focused: 0, Dependents: 0, Dependencies: 0
[2019-03-29 14:25:29.466] unchanged_checked: Focused: 0, Dependents: 0, Dependencies: 0
[2019-03-29 14:25:29.466] Calculating dependencies
[2019-03-29 14:25:29.466] Merging
[2019-03-29 14:25:29.466] Merge skipped 0 of 0 modules
[2019-03-29 14:25:29.466] Done
[2019-03-29 14:25:29.466] Checked set: Focused: 0, Dependents: 0, Dependencies: 0
Found 0 errors
```

**Comment by goodmind** [comment]
@joa do you use local (node_modules) flow or global?

**Comment by joa** [comment]
@goodmind Both actually. This is a `create-react-app` project. For all the tests I did, I use just the standalone version.  Local flow is in sync with my global install.

**Comment by goodmind** [comment]
Well, then I have no other ideas

**Comment by joa** [comment]
@goodmind Apparently my project layout is like this:

- src/app 
- src/comp
- src/sdk

The app and comp folders do have flow coverage and receive errors. Anything within the SDK folder has no coverage whatsoever.

**Comment by goodmind** [comment]
@joa how much of lines files have?

**Comment by joa** [comment]
Approx 100kloc total

**Comment by avikchaudhuri** [comment]
This is strange. I don't have any ideas other than those covered: the obvious things to confirm were that you have @flow headers and are not [ignore]ing these files. Can you run `flow ls` at the top level (wherever your .flowconfig is) and confirm that nothing under src/sdk is in the list?

**Comment by goodmind** [comment]
I have something similar if I use function overloading like this, exported function becomes `any`
```js
declare export function createGraph(opts: {|
  +node: Array<Cmd>,
  +child?: Array<Graph<any>>,
  +from?: Array<Graph<any>>,
|}): Graph<>
declare export function createGraph<Val: {[name: string]: any}>(opts: {|
  +node: Array<Cmd>,
  +child?: Array<Graph<any>>,
  +from?: Array<Graph<any>>,
  +val: Val,
|}): Graph<Val>
export function createGraph({
  node,
  child = [],
  from = [],
  val = {},
}: {|
  +node: Array<Cmd>,
  +child?: Array<Graph<any>>,
  +from?: Array<Graph<any>>,
  val?: {[name: string]: any},
|}): Graph<any> {//implementation}
```

**Comment by goodmind** [comment]
@avikchaudhuri any thoughts?

**Comment by goodmind** [comment]
This isn't reproducible if I use clean project, and use the same overloading

**Comment by joa** [comment]
Yes `flow ls` shows the file. I might find some time next week to bisect this.

**Comment by joa** [comment]
This issue is still labeled [repro needed](https://github.com/facebook/flow/labels/repro%20needed) although @goodmind provided one. 

This is a serious issue as type errors are simply ignored.

**Comment by goodmind** [comment]
@avikchaudhuri

**Comment by simkessy** [comment]
@joa  did you solve this, i have the same issue

**Comment by evbo** [comment]
what happens if you re-run after first doing: `rm -rf /tmp/flow`?

I wonder if old definitions are hanging out in your cache (back when there were no issues)

**Comment by SamChou19815** [comment]
I believe the problem should be fixed by recent version of Flow.

**Comment by kalpanagupta** [comment]
I am facing the same issue with latest version of flow. `flow check ` is reporting error correctly. but `flow status` or `flow` is still failing
